<script setup lang="ts">
import RecordList from '@/shared/ui/RecordList.vue'
import {localTime,chinaInput,deadlinePayload} from '@/shared/ui/presentation'
import {computed,onMounted,ref} from 'vue'
import {currentUser,httpClient} from '@/shared/http/client'
interface Notice {id:number;caseId:string;title:string;read:boolean;createdAt:string}
interface Task {taskKey:string;caseId:string;title:string;version:number;deadline:string|null;overdue:boolean}
const notices=ref<Notice[]>([]),tasks=ref<Task[]>([]),noticeTotal=ref(0),taskTotal=ref(0),noticePage=ref(1),taskPage=ref(1),busy=ref(false),message=ref(''),selected=ref<Task>(),deadline=ref(''),reason=ref(''),history=ref(''),historyPage=ref(1),historyTotal=ref(0)
const cs=computed(()=>currentUser.value?.roles.includes('CUSTOMER_SERVICE'))
async function run(action:()=>Promise<void>){busy.value=true;message.value='';try{await action()}catch(error){message.value=error instanceof Error?error.message:'操作失败'}finally{busy.value=false}}
async function load(){const inbox=(await httpClient.get<{data:{records:Notice[];total:number}}>('/notifications',{params:{page:noticePage.value,size:20}})).data.data;notices.value=inbox.records;noticeTotal.value=inbox.total;const todo=(await httpClient.get<{data:{records:Task[];total:number}}>('/notifications/todos',{params:{page:taskPage.value,size:20}})).data.data;tasks.value=todo.records;taskTotal.value=todo.total}
async function read(id:number){await httpClient.post(`/notifications/${id}/read`,{});await load()}
function choose(task:Task){selected.value=task;deadline.value=chinaInput(task.deadline);reason.value='';history.value='';historyPage.value=1}
async function save(){if(!selected.value)return;if(!reason.value.trim())throw Error('请填写期限变更原因');selected.value=(await httpClient.post<{data:Task}>('/notifications/deadlines',{taskKey:selected.value.taskKey,expectedVersion:selected.value.version,deadline:deadlinePayload(deadline.value),reason:reason.value})).data.data;message.value='期限变更已留历史；自动提醒未开启';await load()}
async function loadHistory(){if(!selected.value)return;const result=(await httpClient.get<{data:{records:unknown[];total:number}}>('/notifications/deadlines/history',{params:{taskKey:selected.value.taskKey,page:historyPage.value,size:20}})).data.data;history.value=JSON.stringify(result.records,null,2);historyTotal.value=result.total}

onMounted(()=>run(load))
</script>
<template><section class="notifications"><details><summary>站内通知与待办 <span v-if="taskTotal">（{{ taskTotal }}项待办）</span></summary><p>自动超时、重复提醒、升级和短信关闭；截止时间可留空，过期仅显示标签。</p><p role="status">{{ message }}</p><button :disabled="busy" @click="run(load)">刷新</button><h3>我的待办（{{ taskTotal }}）</h3><article v-for="task in tasks" :key="task.taskKey"><p>{{ task.title }} · 案件 {{ task.caseId }}</p><p>{{ task.deadline?`截止 ${localTime(task.deadline)}`:'不限期' }} {{ task.overdue?'已逾期':'' }}</p><button v-if="cs" :disabled="busy" @click="choose(task)">设置/修改/清除期限</button></article><button :disabled="busy||taskPage<=1" @click="taskPage--;run(load)">待办上一页</button><button :disabled="busy||taskPage*20>=taskTotal" @click="taskPage++;run(load)">待办下一页</button><div v-if="selected&&cs"><p>{{ selected.title }}</p><label>中国时间截止（留空清除）<input v-model="deadline" type="datetime-local"/></label><label>变更原因<textarea v-model="reason" maxlength="2000"/></label><button :disabled="busy" @click="run(save)">保存期限版本</button><button :disabled="busy" @click="run(loadHistory)">查看历史</button><RecordList :value="history"/><button :disabled="busy||historyPage<=1" @click="historyPage--;run(loadHistory)">历史上一页</button><button :disabled="busy||historyPage*20>=historyTotal" @click="historyPage++;run(loadHistory)">历史下一页</button></div><h3>我的通知（{{ noticeTotal }}）</h3><article v-for="notice in notices" :key="notice.id"><p>{{ notice.title }} · {{ localTime(notice.createdAt) }} · 案件 {{ notice.caseId }}</p><button :disabled="busy||notice.read" @click="run(()=>read(notice.id))">{{ notice.read?'已读':'标记已读' }}</button></article><button :disabled="busy||noticePage<=1" @click="noticePage--;run(load)">通知上一页</button><button :disabled="busy||noticePage*20>=noticeTotal" @click="noticePage++;run(load)">通知下一页</button></details></section></template>
<style scoped>.notifications{position:sticky;top:0;z-index:30;padding:12px 16px;background:#fff;border-bottom:1px solid #ddd}.notifications details[open]{max-height:75vh;overflow:auto}.notifications summary{cursor:pointer;min-height:32px;line-height:32px;font-weight:600}article{border-bottom:1px solid #eee;padding:8px}label{display:block;margin:10px 0}input,textarea{max-width:100%;box-sizing:border-box}pre{white-space:pre-wrap;overflow-wrap:anywhere}button{margin:6px}</style>
