-- Stage 3 catalogue: reuse all phase 2 tables; part code globally unique, separate aliases, M:N models.
CREATE TABLE price_brand (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(64) NOT NULL CHECK(btrim(code) <> ''),
 name VARCHAR(120) NOT NULL CHECK(btrim(name) <> ''),
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT NOT NULL REFERENCES app_user(id), updated_by BIGINT NOT NULL REFERENCES app_user(id),
 UNIQUE(code)
);
CREATE TABLE price_model (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 brand_id BIGINT NOT NULL REFERENCES price_brand(id),
 code VARCHAR(64) NOT NULL CHECK(btrim(code) <> ''),
 name VARCHAR(120) NOT NULL CHECK(btrim(name) <> ''),
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT NOT NULL REFERENCES app_user(id), updated_by BIGINT NOT NULL REFERENCES app_user(id),
 UNIQUE(brand_id,code)
);
CREATE TABLE price_part (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 internal_code VARCHAR(64) NOT NULL CHECK(btrim(internal_code) <> ''),
 name VARCHAR(120) NOT NULL CHECK(btrim(name) <> ''),
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT NOT NULL REFERENCES app_user(id), updated_by BIGINT NOT NULL REFERENCES app_user(id),
 UNIQUE(internal_code)
);
CREATE TABLE price_alias (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 part_id BIGINT NOT NULL REFERENCES price_part(id),
 name VARCHAR(120) NOT NULL CHECK(btrim(name) <> ''),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT NOT NULL REFERENCES app_user(id), updated_by BIGINT NOT NULL REFERENCES app_user(id),
 UNIQUE(part_id,name)
);
CREATE TABLE price_source (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(64) NOT NULL CHECK(btrim(code) <> ''),
 name VARCHAR(120) NOT NULL CHECK(btrim(name) <> ''),
 kind VARCHAR(32) NOT NULL CHECK(kind IN ('MANUAL','CSV','EXCEL','HISTORICAL_CASE')),
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT REFERENCES app_user(id), updated_by BIGINT REFERENCES app_user(id),
 UNIQUE(code)
);

CREATE TABLE price_part_model (
 part_id BIGINT NOT NULL REFERENCES price_part(id), model_id BIGINT NOT NULL REFERENCES price_model(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL REFERENCES app_user(id),
 PRIMARY KEY(part_id,model_id)
);
CREATE INDEX idx_price_model_brand ON price_model(brand_id,id);
CREATE INDEX idx_price_part_model_model ON price_part_model(model_id,part_id);
CREATE INDEX idx_price_alias_name ON price_alias(name,part_id,id);
-- Prefix searches are literal (wildcards escaped), do not silently choose an alias match.
CREATE INDEX idx_price_alias_prefix ON price_alias(name varchar_pattern_ops,id);
CREATE INDEX idx_price_part_name_prefix ON price_part(name varchar_pattern_ops,id);
INSERT INTO price_source(code,name,kind) VALUES
 ('MANUAL','手工维护','MANUAL'),('CSV','CSV 导入','CSV'),('EXCEL','Excel 导入','EXCEL'),
 ('HISTORICAL_CASE','历史案件导入','HISTORICAL_CASE');
