-- Logical key: part/model/type/scope/region/shop. NULLS NOT DISTINCT makes NATIONAL unique.
-- Append versions only: from strictly increases; finite intervals are inclusive and cannot overlap.
-- Only a linked new version may close an unbounded predecessor. No amount/source/creator overwrite.
CREATE TABLE price_record (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 part_id BIGINT NOT NULL, model_id BIGINT NOT NULL,
 price_type VARCHAR(48) NOT NULL CHECK(price_type IN ('REPAIR_SHOP_RAW_REFERENCE','PLATFORM_EXTERNAL_REFERENCE','INSURER_HISTORICAL_ASSESSED','REPAIR_SHOP_SETTLEMENT_REFERENCE')),
 scope VARCHAR(16) NOT NULL CHECK(scope IN ('NATIONAL','REGION','SHOP')),
 region_id BIGINT REFERENCES region(id), shop_id BIGINT REFERENCES repair_shop(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL REFERENCES app_user(id),
 FOREIGN KEY(part_id,model_id) REFERENCES price_part_model(part_id,model_id),
 UNIQUE NULLS NOT DISTINCT(part_id,model_id,price_type,scope,region_id,shop_id),
 CHECK((scope='NATIONAL' AND region_id IS NULL AND shop_id IS NULL) OR
       (scope='REGION' AND region_id IS NOT NULL AND shop_id IS NULL) OR
       (scope='SHOP' AND shop_id IS NOT NULL AND region_id IS NULL))
);
CREATE TABLE price_import_preview (
 id UUID PRIMARY KEY, actor_id BIGINT NOT NULL REFERENCES app_user(id),
 file_name VARCHAR(120) NOT NULL, file_format VARCHAR(8) NOT NULL CHECK(file_format IN ('CSV','EXCEL')),
 sha256 VARCHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ, total_rows INTEGER NOT NULL CHECK(total_rows BETWEEN 1 AND 20000)
);
CREATE INDEX idx_price_preview_expiry ON price_import_preview(expires_at);
CREATE TABLE price_import_preview_row (
 preview_id UUID NOT NULL REFERENCES price_import_preview(id), row_number INTEGER NOT NULL,
 raw_values JSONB NOT NULL, result JSONB NOT NULL, PRIMARY KEY(preview_id,row_number)
);
CREATE TABLE price_import_batch (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 preview_id UUID NOT NULL UNIQUE REFERENCES price_import_preview(id),
 file_name VARCHAR(120) NOT NULL, source VARCHAR(8) NOT NULL CHECK(source IN ('CSV','EXCEL')), sha256 VARCHAR(64) NOT NULL,
 status VARCHAR(16) NOT NULL CHECK(status IN ('SUCCESS','FAILED')),
 total_rows INTEGER NOT NULL CHECK(total_rows BETWEEN 1 AND 20000),
 success_count INTEGER NOT NULL CHECK(success_count>=0), failure_count INTEGER NOT NULL CHECK(failure_count>=0),
 actor_id BIGINT NOT NULL REFERENCES app_user(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(success_count+failure_count=total_rows),
 CHECK((status='SUCCESS' AND success_count=total_rows) OR (status='FAILED' AND success_count=0))
);
CREATE INDEX idx_price_batch_actor ON price_import_batch(actor_id,id DESC);
CREATE TABLE price_import_error (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id BIGINT NOT NULL REFERENCES price_import_batch(id), row_number INTEGER NOT NULL,
 field VARCHAR(64) NOT NULL, reason VARCHAR(500) NOT NULL, original_value VARCHAR(256)
);
CREATE INDEX idx_price_import_error_batch ON price_import_error(batch_id,row_number,id);
CREATE TABLE price_version (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 record_id BIGINT NOT NULL REFERENCES price_record(id), version_no INTEGER NOT NULL CHECK(version_no>0),
 amount NUMERIC(18,2) NOT NULL CHECK(amount>0), currency VARCHAR(3) NOT NULL DEFAULT 'CNY' CHECK(currency='CNY'),
 source_id BIGINT NOT NULL REFERENCES price_source(id), source_code VARCHAR(64) NOT NULL, source_name VARCHAR(120) NOT NULL,
 source_kind VARCHAR(32) NOT NULL CHECK(source_kind IN ('MANUAL','CSV','EXCEL','HISTORICAL_CASE')),
 effective_from DATE NOT NULL CHECK(effective_from BETWEEN DATE '0001-01-01' AND DATE '9999-12-31'),
 effective_to DATE CHECK(effective_to BETWEEN effective_from AND DATE '9999-12-31'),
 previous_version_id BIGINT REFERENCES price_version(id) DEFERRABLE INITIALLY DEFERRED,
 closed_by_version_id BIGINT REFERENCES price_version(id) DEFERRABLE INITIALLY DEFERRED,
 batch_id BIGINT REFERENCES price_import_batch(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL REFERENCES app_user(id),
 UNIQUE(record_id,version_no), UNIQUE(record_id,effective_from),
 CHECK(closed_by_version_id IS NULL OR effective_to IS NOT NULL),
 -- Native range operator classes avoid requiring btree_gist extension/extra DB privileges.
 EXCLUDE USING gist (int8range(record_id,record_id,'[]') WITH &&, daterange(effective_from,effective_to,'[]') WITH &&)
);
CREATE INDEX idx_price_version_record ON price_version(record_id,version_no DESC);
CREATE INDEX idx_price_version_dates ON price_version USING gist(daterange(effective_from,effective_to,'[]'));
CREATE INDEX idx_price_version_batch ON price_version(batch_id,id);
CREATE INDEX idx_price_record_model_type ON price_record(model_id,price_type,part_id,id);
CREATE INDEX idx_price_record_part_type ON price_record(part_id,price_type,model_id,id);
CREATE INDEX idx_price_record_region ON price_record(region_id,price_type,model_id,id) WHERE scope='REGION';
CREATE INDEX idx_price_record_shop ON price_record(shop_id,price_type,model_id,id) WHERE scope='SHOP';
CREATE INDEX idx_price_record_type ON price_record(price_type,id);
CREATE INDEX idx_price_record_scope ON price_record(scope,id);

CREATE FUNCTION protect_price_record() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Price identity is immutable' USING ERRCODE='23514'; END; $$;
CREATE TRIGGER price_record_immutable BEFORE UPDATE OR DELETE ON price_record FOR EACH ROW EXECUTE FUNCTION protect_price_record();

CREATE FUNCTION protect_price_version() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE prior price_version;
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Historical price cannot be deleted' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' THEN
  IF OLD.effective_to IS NOT NULL OR NEW.effective_to IS NULL OR NEW.closed_by_version_id IS NULL OR
     (to_jsonb(NEW)-'effective_to'-'closed_by_version_id') IS DISTINCT FROM (to_jsonb(OLD)-'effective_to'-'closed_by_version_id')
  THEN RAISE EXCEPTION 'Historical price fields are immutable; only linked expiry may be completed' USING ERRCODE='23514'; END IF;
  RETURN NEW;
 END IF;
 PERFORM id FROM price_record WHERE id=NEW.record_id FOR UPDATE;
 SELECT * INTO prior FROM price_version WHERE record_id=NEW.record_id ORDER BY version_no DESC LIMIT 1;
 IF prior.id IS NULL THEN
  IF NEW.version_no<>1 OR NEW.previous_version_id IS NOT NULL THEN RAISE EXCEPTION 'First version must be 1' USING ERRCODE='23514'; END IF;
 ELSE
  IF NEW.version_no<>prior.version_no+1 OR NEW.previous_version_id IS DISTINCT FROM prior.id OR NEW.effective_from<=prior.effective_from
  THEN RAISE EXCEPTION 'New version must follow latest version with a later start date' USING ERRCODE='23514'; END IF;
 END IF;
 IF NOT EXISTS(SELECT 1 FROM price_source s WHERE s.id=NEW.source_id AND s.enabled AND s.code=NEW.source_code AND s.name=NEW.source_name AND s.kind=NEW.source_kind)
 THEN RAISE EXCEPTION 'Source snapshot must match enabled source' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER price_version_protected BEFORE INSERT OR UPDATE OR DELETE ON price_version FOR EACH ROW EXECUTE FUNCTION protect_price_version();
CREATE FUNCTION validate_price_closure() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.closed_by_version_id IS NOT NULL AND NOT EXISTS(
  SELECT 1 FROM price_version n WHERE n.id=NEW.closed_by_version_id AND n.record_id=NEW.record_id
    AND n.previous_version_id=NEW.id AND n.version_no=NEW.version_no+1 AND n.effective_from=NEW.effective_to+1)
 THEN RAISE EXCEPTION 'Expiry completion requires the linked successor at next day' USING ERRCODE='23514'; END IF;
 RETURN NULL;
END; $$;
CREATE CONSTRAINT TRIGGER price_closure_link AFTER INSERT OR UPDATE ON price_version DEFERRABLE INITIALLY DEFERRED
 FOR EACH ROW EXECUTE FUNCTION validate_price_closure();
