package com.evinsurance.platform.quotation.application;

import com.evinsurance.platform.quotation.api.QuotationRequests;
import com.evinsurance.platform.quotation.domain.*;
import com.evinsurance.platform.quotation.infrastructure.*;
import com.evinsurance.platform.quotation.infrastructure.QuotationRows.*;
import com.evinsurance.platform.workorder.infrastructure.*;
import com.evinsurance.platform.document.infrastructure.FileMapper;
import com.evinsurance.platform.document.application.FileService;
import com.evinsurance.platform.foundation.api.*;
import com.evinsurance.platform.foundation.web.TraceContext;
import com.evinsurance.platform.identity.domain.*;
import com.evinsurance.platform.audit.application.AuditService;
import com.evinsurance.platform.audit.application.AuditService.Action;
import java.util.*;
import java.util.function.Supplier;
import java.math.BigDecimal;
import java.time.Instant;
import tools.jackson.databind.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class QuotationService {
    private final QuotationMapper mapper;private final WorkOrderMapper orders;private final FileMapper files;private final QuotationLifecycle lifecycle;private final AuditService audit;private final ObjectMapper json;
    public QuotationService(QuotationMapper mapper,WorkOrderMapper orders,FileMapper files,QuotationLifecycle lifecycle,AuditService audit,ObjectMapper json){this.mapper=mapper;this.orders=orders;this.files=files;this.lifecycle=lifecycle;this.audit=audit;this.json=json;}
    private boolean staff(CurrentUser a){return a.roles().contains(Role.ADMIN)||a.roles().contains(Role.CUSTOMER_SERVICE);}
    private void customerService(){if(!CurrentUser.require().roles().contains(Role.CUSTOMER_SERVICE))throw ApiException.denied();}
    private WorkOrderEntity visible(UUID id,boolean lock){var row=lock?orders.lock(id):orders.find(id);if(row==null)throw ApiException.missing("Work order");var a=CurrentUser.require();if(staff(a)){if("DRAFT".equals(row.getStatus()))throw ApiException.denied();return row;}var assignment=orders.activeAssignment(id);if(a.roles().contains(Role.REPAIR_SHOP)&&a.shopId()!=null&&a.shopId().equals(row.getShopId())&&assignment!=null&&assignment.getShopId().equals(a.shopId()))return row;throw ApiException.denied();}
    private WorkOrderRows.Assignment shopAssignment(WorkOrderEntity order,Integer version){var a=CurrentUser.require();var assignment=orders.activeAssignment(order.getId());if(!a.roles().contains(Role.REPAIR_SHOP)||a.shopId()==null||!a.shopId().equals(order.getShopId())||assignment==null||!"ACCEPTED".equals(assignment.getStatus())||!Objects.equals(version,assignment.getAssignmentVersion()))throw ApiException.denied();return assignment;}
    private Context context(UUID id,boolean ensure){if(ensure)mapper.ensure(id);var c=mapper.context(id);if(c==null){c=new Context();c.workOrderId=id;}return c;}
    private void expected(Context c,Integer version){if(version==null||version!=c.version)throw ApiException.conflict("QUOTE_VERSION_CONFLICT","Expected current quotation context version is required");}
    private BigDecimal money(JsonNode value){if(value==null||!value.isTextual())throw ApiException.invalid("Amounts must be decimal strings in CNY yuan");return QuoteCalculator.input(value.asText());}
    private List<QuoteCalculator.Line> lines(List<QuotationRequests.Line> request){if(request==null||request.isEmpty()||request.size()>1000)throw ApiException.invalid("A quote requires 1..1000 lines");var list=new ArrayList<QuoteCalculator.Line>();int index=0;for(var line:request){if(line==null||line.quantity()==null||!line.quantity().isIntegralNumber()||!line.quantity().canConvertToInt()||line.quantity().asInt()<1)throw ApiException.invalid("Quantity must be a positive 32-bit integer");list.add(new QuoteCalculator.Line(++index,line.description(),line.quantity().asInt(),money(line.unitPrice())));}return list;}
    private JsonNode command(UUID caseId,String operation,String key,Object request,Supplier<JsonNode> action){FileService.checkKey(key);var actor=CurrentUser.require();String hash=FileService.hash((caseId+":"+json.writeValueAsString(request)).getBytes(java.nio.charset.StandardCharsets.UTF_8));var prior=mapper.command(actor.id(),operation,key);if(prior!=null){if(!hash.equals(prior.get("request_hash")))throw ApiException.conflict("IDEMPOTENCY_CONFLICT","Key belongs to a different quotation request");return json.readTree((String)prior.get("response_json"));}var result=action.get();mapper.insertCommand(actor.id(),operation,key,hash,json.writeValueAsString(result));return result;}
    private void event(Context c,String kind,String summary,Action action){var actor=CurrentUser.require();mapper.event(c.workOrderId,c.basisVersion,kind,summary,actor.id());audit.record(actor,action,"WORK_ORDER",c.workOrderId,summary);}
    private void status(WorkOrderEntity row,String next,String action){if(row.getStatus().equals(next))return;var actor=CurrentUser.require();var now=Instant.now();String from=row.getStatus();if(orders.transition(row.getId(),row.getVersion(),from,next,row.getShopId(),false,actor.id(),now)!=1)throw ApiException.conflict("WORK_ORDER_STATE_CONFLICT","Work order changed concurrently");orders.insertHistory(row.getId(),from,next,action,null,actor.id(),actor.roles().stream().map(Enum::name).sorted().collect(java.util.stream.Collectors.joining(",")),assignmentVersion(row.getId()),TraceContext.currentTraceId()==null?UUID.randomUUID().toString():TraceContext.currentTraceId(),now);row.setStatus(next);row.setVersion(row.getVersion()+1);}
    private Integer assignmentVersion(UUID id){var a=orders.activeAssignment(id);return a==null?null:a.getAssignmentVersion();}
    private RepairAuthorizationGate.Evidence evidence(Context c){return new RepairAuthorizationGate.Evidence(files.activeCount(c.workOrderId,"LOSS_ASSESSMENT")>0,c.assessmentId!=null,c.insurerConfirmed,c.serviceConfirmed);}
    public JsonNode get(UUID id){return view(visible(id,false));}
    private JsonNode rawView(Raw raw){if(raw==null)return json.nullNode();var out=json.createObjectNode();out.put("id",raw.id().toString()).put("version",raw.versionNo()).put("assignmentVersion",raw.assignmentVersion()).put("currency","CNY").put("unit","yuan").put("total",raw.total().toPlainString());var items=out.putArray("lines");for(var line:mapper.rawItems(raw.id())){var item=items.addObject();item.put("sequence",line.lineNo()).put("description",line.description()).put("quantity",line.quantity()).put("unitPrice",line.unitPrice().toPlainString()).put("amount",line.amount().toPlainString());item.set("priceSnapshot",json.readTree(line.sourceSnapshot()));}return out;}
    private JsonNode formalView(Formal quote){if(quote==null)return json.nullNode();var out=json.createObjectNode();out.put("id",quote.id().toString()).put("version",quote.versionNo()).put("rawQuoteId",quote.rawQuoteId().toString()).put("currency","CNY").put("unit","yuan").put("mode",quote.markupMode()).put("markupValue",quote.markupValue().toPlainString()).put("originalTotal",quote.originalTotal().toPlainString()).put("markupAmount",quote.markupAmount().toPlainString()).put("total",quote.total().toPlainString()).put("calculationVersion",quote.calculationVersion()).put("lineAmountIsAuthoritative",true);var items=out.putArray("lines");for(var line:mapper.formalItems(quote.id()))items.addObject().put("sequence",line.lineNo()).put("description",line.description()).put("quantity",line.quantity()).put("originalUnitPrice",line.originalUnitPrice().toPlainString()).put("originalAmount",line.originalAmount().toPlainString()).put("allocatedMarkup",line.allocatedMarkup().toPlainString()).put("externalUnitPrice",line.externalUnitPrice().toPlainString()).put("externalAmount",line.externalAmount().toPlainString());return out;}
    private JsonNode view(WorkOrderEntity order){var actor=CurrentUser.require();var c=context(order.getId(),false);var out=json.createObjectNode();out.put("caseId",order.getId().toString()).put("status",order.getStatus()).put("version",c.version).put("basisVersion",c.basisVersion);Integer assignment=assignmentVersion(order.getId());if(assignment!=null)out.put("assignmentVersion",assignment);var raw=c.rawQuoteId==null?null:mapper.raw(c.rawQuoteId);if(!staff(actor)&&raw!=null&&(!Objects.equals(actor.shopId(),raw.shopId())||!Objects.equals(assignment,raw.assignmentVersion())))raw=null;out.set("rawQuote",rawView(raw));var gate=evidence(c);var g=out.putObject("gate");g.put("lossAssessmentFileUploaded",gate.lossAssessmentFileUploaded()).put("finalAssessmentAmountRecorded",gate.finalAssessmentAmountRecorded()).put("insurerConfirmationRecorded",gate.insurerConfirmationRecorded()).put("customerServiceConfirmationRecorded",gate.customerServiceConfirmationRecorded()).put("allowed",RepairAuthorizationGate.allowed(gate));g.set("missing",json.valueToTree(RepairAuthorizationGate.missing(gate)));out.put("authorized",c.authorized&&(!Set.of("COMPLETED","CANCELLED","CLOSED").contains(order.getStatus())));if(staff(actor)){out.set("formalQuote",formalView(c.formalQuoteId==null?null:mapper.formal(c.formalQuoteId)));if(c.assessmentId!=null){var assessment=mapper.assessment(c.assessmentId);out.putObject("assessment").put("id",assessment.id().toString()).put("version",assessment.versionNo()).put("amount",assessment.amount().toPlainString()).set("fileSnapshot",json.readTree(assessment.fileSnapshot()));}}return out;}

    @Transactional public JsonNode submitRaw(UUID id,QuotationRequests.Raw request,String key){var order=visible(id,true);var assignment=shopAssignment(order,request.assignmentVersion());return command(id,"RAW",key,request,()->{lifecycle.requireEditable(order);var c=context(id,true);expected(c,request.expectedVersion());var input=lines(request.lines());var calculation=QuoteCalculator.calculate(input,QuoteCalculator.Mode.FIXED_AMOUNT,BigDecimal.ZERO.setScale(2));UUID quoteId=UUID.randomUUID();mapper.insertRaw(quoteId,id,mapper.nextVersion(id,"RAW"),assignment.getShopId(),assignment.getAssignmentVersion(),calculation.originalTotal(),CurrentUser.require().id());for(var line:calculation.lines())mapper.insertRawItem(quoteId,line.sequence(),line.description(),line.quantity(),line.originalUnitPrice(),line.originalAmount(),json.writeValueAsString(Map.of("source","SHOP_MANUAL","shopId",assignment.getShopId(),"assignmentVersion",assignment.getAssignmentVersion(),"currency","CNY","unitPrice",line.originalUnitPrice().toPlainString())));lifecycle.invalidate(c,"RAW_QUOTE_CHANGED");c.rawQuoteId=quoteId;c.formalQuoteId=null;lifecycle.save(c);status(order,"QUOTE_REVIEWING","QUOTE_RAW_SUBMIT");event(c,"RAW_SUBMITTED","Immutable raw quote version submitted",Action.QUOTE_RAW_SUBMIT);return view(order);});}
    @Transactional public JsonNode issueFormal(UUID id,QuotationRequests.Formal request,String key){customerService();var order=visible(id,true);return command(id,"FORMAL",key,request,()->{lifecycle.requireEditable(order);var c=context(id,true);expected(c,request.expectedVersion());if(c.rawQuoteId==null||!c.rawQuoteId.equals(request.rawQuoteId()))throw ApiException.conflict("QUOTE_VERSION_CONFLICT","Review the current raw quote version");var raw=mapper.raw(c.rawQuoteId);var assignment=orders.activeAssignment(id);if(assignment==null||raw.shopId()!=assignment.getShopId()||raw.assignmentVersion()!=assignment.getAssignmentVersion())throw ApiException.conflict("STALE_ASSIGNMENT","Quote belongs to a previous assignment");var material=files.missingReason(id);if(files.activeCount(id,"NOTICE")==0&&(material==null||material.isBlank()))throw ApiException.conflict("MISSING_NOTICE","Upload a notice or record its missing reason before quote review");QuoteCalculator.Mode mode;try{mode=QuoteCalculator.Mode.valueOf(request.mode());}catch(Exception e){throw ApiException.invalid("Choose FIXED_AMOUNT or PERCENTAGE");}boolean fixed=request.fixedAmount()!=null&&!request.fixedAmount().isNull(),rate=request.percentage()!=null&&!request.percentage().isNull();if((mode==QuoteCalculator.Mode.FIXED_AMOUNT&&(!fixed||rate))||(mode==QuoteCalculator.Mode.PERCENTAGE&&(!rate||fixed)))throw ApiException.invalid("Exactly one markup value for the selected mode is required");var value=money(mode==QuoteCalculator.Mode.FIXED_AMOUNT?request.fixedAmount():request.percentage());var lines=mapper.rawItems(raw.id()).stream().map(x->new QuoteCalculator.Line(x.lineNo(),x.description(),x.quantity(),x.unitPrice())).toList();var calculation=QuoteCalculator.calculate(lines,mode,value);UUID quoteId=UUID.randomUUID();mapper.insertFormal(quoteId,id,mapper.nextVersion(id,"FORMAL"),raw.id(),mode.name(),value,calculation.originalTotal(),calculation.markupAmount(),calculation.total(),CurrentUser.require().id());for(var line:calculation.lines())mapper.insertFormalItem(quoteId,line);lifecycle.invalidate(c,"FORMAL_QUOTE_CHANGED");c.formalQuoteId=quoteId;lifecycle.save(c);status(order,"WAITING_INSURER_ASSESSMENT","QUOTE_FORMAL_ISSUE");event(c,"FORMAL_ISSUED","Immutable formal quote issued; algorithm=PRO_RATA_LARGEST_REMAINDER_V1",Action.QUOTE_FORMAL_ISSUE);return view(order);});}
    @Transactional public JsonNode assess(UUID id,QuotationRequests.Assessment request,String key){customerService();var order=visible(id,true);return command(id,"ASSESSMENT",key,request,()->{lifecycle.requireEditable(order);var c=context(id,true);expected(c,request.expectedVersion());var amount=money(request.amount());UUID assessmentId=UUID.randomUUID();mapper.insertAssessment(assessmentId,id,mapper.nextVersion(id,"ASSESSMENT"),c.formalQuoteId,amount,json.writeValueAsString(mapper.activeLossFiles(id)),CurrentUser.require().id());lifecycle.invalidate(c,"ASSESSMENT_CHANGED");c.assessmentId=assessmentId;lifecycle.save(c);status(order,"WAITING_REPAIR_AUTHORIZATION","QUOTE_ASSESSMENT_RECORD");event(c,"ASSESSMENT_RECORDED","Immutable loss assessment amount version recorded",Action.QUOTE_ASSESSMENT_RECORD);return view(order);});}
    @Transactional public JsonNode confirm(UUID id,String kind,QuotationRequests.Confirm request,String key){customerService();if(!Set.of("INSURER","CUSTOMER_SERVICE").contains(kind))throw ApiException.invalid("Invalid confirmation kind");var order=visible(id,true);return command(id,"CONFIRM_"+kind,key,request,()->{lifecycle.requireEditable(order);var c=context(id,true);expected(c,request.expectedVersion());if(("INSURER".equals(kind)&&c.insurerConfirmed)||("CUSTOMER_SERVICE".equals(kind)&&c.serviceConfirmed))return view(order);mapper.confirmation(UUID.randomUUID(),c,kind,json.writeValueAsString(mapper.activeLossFiles(id)),CurrentUser.require().id());if("INSURER".equals(kind))c.insurerConfirmed=true;else c.serviceConfirmed=true;event(c,kind+"_CONFIRMED","Confirmation recorded against basis="+c.basisVersion,"INSURER".equals(kind)?Action.QUOTE_INSURER_CONFIRM:Action.QUOTE_SERVICE_CONFIRM);if(RepairAuthorizationGate.allowed(evidence(c))&&!c.authorized){c.authorized=true;event(c,"AUTHORIZATION_GRANTED","All four authorization prerequisites satisfied",Action.REPAIR_AUTHORIZATION_GRANTED);status(order,"WAITING_REPAIR_AUTHORIZATION","REPAIR_AUTHORIZATION_GRANTED");}lifecycle.save(c);return view(order);});}
    @Transactional public JsonNode start(UUID id,QuotationRequests.Start request,String key){var order=visible(id,true);shopAssignment(order,request.assignmentVersion());return command(id,"START",key,request,()->{lifecycle.requireEditable(order);var c=context(id,true);expected(c,request.expectedVersion());var missing=RepairAuthorizationGate.missing(evidence(c));if(!missing.isEmpty())throw ApiException.conflict("REPAIR_GATE_INCOMPLETE","Missing repair prerequisites: "+missing);status(order,"REPAIRING","REPAIR_START");event(c,"REPAIR_STARTED","Repair started by current accepted assignment",Action.REPAIR_START);lifecycle.save(c);return view(order);});}
    public PageResponse<Map<String,Object>> history(UUID id,String type,int page,int size){visible(id,false);if(!Set.of("RAW","FORMAL","ASSESSMENT","CONFIRMATION","EVENT").contains(type))throw ApiException.invalid("Invalid history type");var actor=CurrentUser.require();Long shop=null;Integer assignment=null;if(!staff(actor)){if(!"RAW".equals(type))throw ApiException.denied();shop=actor.shopId();assignment=assignmentVersion(id);}int offset=PageResponse.offset(page,size);var rows=mapper.history(id,type,shop,assignment,offset,size);for(var row:rows)row.replaceAll((k,v)->v instanceof BigDecimal decimal?decimal.toPlainString():v);return new PageResponse<>(page,size,mapper.historyCount(id,type,shop,assignment),rows);}
    public String export(UUID id,UUID quoteId){visible(id,false);if(!staff(CurrentUser.require()))throw ApiException.denied();var quote=mapper.formal(quoteId);if(quote==null||!quote.workOrderId().equals(id))throw ApiException.missing("Formal quote");StringBuilder csv=new StringBuilder("sequence,description,quantity,external_unit_price,external_line_amount,currency\r\n");for(var line:mapper.formalItems(quoteId))csv.append(line.lineNo()).append(',').append(csvText(line.description())).append(',').append(line.quantity()).append(',').append(line.externalUnitPrice().toPlainString()).append(',').append(line.externalAmount().toPlainString()).append(",CNY\r\n");csv.append("TOTAL,,,,").append(quote.total().toPlainString()).append(",CNY\r\nNOTE,\"Line amount is authoritative; displayed unit price has 6 decimal places\"\r\n");audit.record(CurrentUser.require(),Action.QUOTE_EXTERNAL_EXPORT,"FORMAL_QUOTE",quoteId,"External-only CSV; version="+quote.versionNo());return csv.toString();}
    private String csvText(String value){String text=value;if(!text.stripLeading().isEmpty() && "=+@-".indexOf(text.stripLeading().charAt(0))>=0)text="'"+text;return "\""+text.replace("\"","\"\"")+"\"";}
}
