<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'
import {currentUser,httpClient} from '@/shared/http/client'
import {formalPayload,quotationApi,type QuoteCase} from './quotation'
const props=defineProps<{caseId:string;refreshToken?:number}>(),emit=defineEmits<{changed:[]}>(),api=quotationApi(httpClient,props.caseId)
const cs=computed(()=>currentUser.value?.roles.includes('CUSTOMER_SERVICE')),staff=computed(()=>cs.value||currentUser.value?.roles.includes('ADMIN')),shop=computed(()=>currentUser.value?.roles.includes('REPAIR_SHOP'))
const data=ref<QuoteCase>(),busy=ref(false),message=ref(''),rawText=ref('[{"description":"","quantity":1,"unitPrice":"0.00"}]'),mode=ref<'FIXED_AMOUNT'|'PERCENTAGE'>('FIXED_AMOUNT'),markup=ref('0.00'),assessment=ref(''),historyType=ref(shop.value?'RAW':'EVENT'),historyPage=ref(1),historyTotal=ref(0),history=ref('')
const editable=computed(()=>data.value&&['ARRIVED','WAITING_QUOTE','QUOTE_REVIEWING','WAITING_INSURER_ASSESSMENT','WAITING_REPAIR_AUTHORIZATION'].includes(data.value.status))
async function load(){data.value=await api.get()}
async function run(action:()=>Promise<void>){busy.value=true;message.value='';try{await action()}catch(e){message.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
async function post(path:string,body:unknown){data.value=await api.post(path,body);message.value='已保存；历史版本保留';emit('changed')}
async function submit(){if(!data.value)return;await post('raw-quotes',{expectedVersion:data.value.version,assignmentVersion:data.value.assignmentVersion,lines:JSON.parse(rawText.value)})}
async function approve(){if(!data.value?.rawQuote)throw Error('需先有当前网点原始报价');await post('formal-quotes',formalPayload(data.value.version,data.value.rawQuote.id,mode.value,markup.value))}
async function recordAssessment(){if(!data.value)return;await post('assessments',{expectedVersion:data.value.version,amount:assessment.value})}
async function confirm(kind:'INSURER'|'CUSTOMER_SERVICE'){if(!data.value)return;await post(`confirmations/${kind}`,{expectedVersion:data.value.version})}
async function start(){if(!data.value)return;await post('start-repair',{expectedVersion:data.value.version,assignmentVersion:data.value.assignmentVersion})}
async function loadHistory(){const result=await api.history(historyType.value,historyPage.value);historyTotal.value=result.total;history.value=JSON.stringify(result.records,null,2)}
async function exportCsv(){if(!data.value?.formalQuote)return;const blob=await api.export(data.value.formalQuote.id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`quote-v${data.value.formalQuote.version}.csv`;a.click();URL.revokeObjectURL(url)}
onMounted(()=>run(load));watch(()=>props.refreshToken,()=>run(load))
</script>
<template><section class="quotation"><h2>报价、核损与维修授权</h2><button :disabled="busy" @click="run(load)">刷新当前版本</button><p role="status">{{ message }}</p><template v-if="data"><p>状态 {{ data.status }}；上下文版本 {{ data.version }}；确认依据版本 {{ data.basisVersion }}</p><p>币种 CNY，单位元；金额来自后端。正式对外行金额为准，展示单价保留6位。</p>
<div v-if="data.rawQuote"><h3>网点原始报价 v{{ data.rawQuote.version }}</h3><p>原始合计 {{ data.rawQuote.total }} 元</p><pre>{{ JSON.stringify(data.rawQuote.lines,null,2) }}</pre></div><div v-if="shop&&editable"><h3>提交原始报价新版本</h3><p>明细JSON：description、整数quantity、字符串unitPrice。客服不能改原价；每次提交保留新版本。</p><textarea v-model="rawText" rows="7" aria-label="原始报价明细JSON"/><button :disabled="busy" @click="run(submit)">网点提交报价</button></div>
<div v-if="staff"><template v-if="data.formalQuote"><h3>正式报价 v{{ data.formalQuote.version }}（内部审核）</h3><p>原始合计 {{ data.formalQuote.originalTotal }}；加价 {{ data.formalQuote.markupAmount }}；对外总额 {{ data.formalQuote.total }} 元</p><pre>{{ JSON.stringify(data.formalQuote.lines,null,2) }}</pre><button :disabled="busy" @click="run(exportCsv)">导出仅对外价格的 CSV 数据</button></template><div v-if="cs&&editable"><h3>客服审核与总额加价</h3><select v-model="mode"><option value="FIXED_AMOUNT">固定金额（元）</option><option value="PERCENTAGE">比例（10.00代表10%）</option></select><input v-model="markup" inputmode="decimal" aria-label="加价值"><button :disabled="busy||!data.rawQuote" @click="run(approve)">审核并生成正式新版本</button><h3>最终核损金额</h3><input v-model="assessment" inputmode="decimal" placeholder="金额字符串，最多2位小数"><button :disabled="busy" @click="run(recordAssessment)">保存核损新版本</button><p>报价、核损金额或核损材料变化会清除两项确认并撤销旧授权。</p><button :disabled="busy||data.gate.insurerConfirmationRecorded" @click="run(()=>confirm('INSURER'))">代录保司确认</button><button :disabled="busy||data.gate.customerServiceConfirmationRecorded" @click="run(()=>confirm('CUSTOMER_SERVICE'))">客服确认当前依据</button></div><p v-if="data.assessment">最终核损 v{{ data.assessment.version }}：{{ data.assessment.amount }} 元</p></div>
<h3>四项开修条件</h3><ul><li>核损单上传：{{ data.gate.lossAssessmentFileUploaded?'是':'否' }}</li><li>最终核损金额已录入：{{ data.gate.finalAssessmentAmountRecorded?'是':'否' }}</li><li>保司确认已代录：{{ data.gate.insurerConfirmationRecorded?'是':'否' }}</li><li>客服已确认：{{ data.gate.customerServiceConfirmationRecorded?'是':'否' }}</li></ul><p>{{ data.authorized?'当前已授权':'当前未授权' }}；开修后不开放报价/核损常规修改。</p><button v-if="shop&&editable" :disabled="busy||!data.gate.allowed" @click="run(start)">开修（后端再次检查）</button>
<details><summary>版本、确认及授权历史</summary><select v-model="historyType"><option value="RAW">原始报价</option><template v-if="staff"><option value="FORMAL">正式报价</option><option value="ASSESSMENT">核损</option><option value="CONFIRMATION">确认</option><option value="EVENT">授权/变更事件</option></template></select><input v-model.number="historyPage" type="number" min="1" aria-label="历史页码"><button :disabled="busy" @click="run(loadHistory)">查询历史</button><span>共 {{ historyTotal }} 条</span><pre>{{ history }}</pre></details></template></section></template>
<style scoped>.quotation{padding:20px;margin:20px 0;border:1px solid #ddd}input,select,button{margin:6px;max-width:100%}textarea{width:100%;box-sizing:border-box}pre{white-space:pre-wrap;overflow-wrap:anywhere}h3{margin-top:20px}</style>
