const states: Record<string,string>={IDENTIFIER_CONFLICT:'报案号与工单号不一致，需人工核对',INVALID_ARGUMENT:'输入格式不正确',TRANSACTION_CONFLICT:'流水号与已有内容冲突',FUNDS_EXCESS:'金额超过当前应收/应付目标',FUNDS_TARGET_UNSET:'应收/应付金额尚未明确',FUNDS_INSURER_UNSETTLED:'保险回款尚未结清',DATABASE_CONFLICT:'数据冲突，请核对后重试',DRAFT:'草稿',PENDING_DISPATCH:'待派单',PENDING_ACCEPTANCE:'待接单',PENDING_ARRIVAL:'待到店',ARRIVAL_EXCEPTION:'到店异常',ARRIVED:'已到店',WAITING_QUOTE:'待报价',QUOTE_REVIEWING:'报价审核中',WAITING_INSURER_ASSESSMENT:'等待保司核损',WAITING_REPAIR_AUTHORIZATION:'待维修授权',REPAIRING:'维修中',WAITING_OWNER_CONFIRMATION:'待收车确认',COMPLETED:'已完成',CANCELLED:'已取消',CLOSED:'已关闭',SUBMITTED:'已提交',PROCESSING:'处理中',RESOLVED:'已解决',RECORDED:'已记账',DUPLICATE:'重复，未重复记账',NEEDS_REVIEW:'待人工核对',READY:'待确认',INVALID:'格式不正确',FAILED:'处理失败',UNSET:'金额未定',UNPAID:'未收付',PARTIAL:'部分收付',SETTLED:'已结清',RECEIVE:'保司→平台',PAY:'平台→网点',ACTIVE:'有效',SUPERSEDED:'已替换',VOID:'已作废',SUCCEEDED:'识别成功',QUEUED:'排队中',RUNNING:'处理中',CUSTOMER_SERVICE_CORRECTION:'客服纠正',OWNER:'车主',CUSTOMER_SERVICE:'客服',ADMIN:'管理员',REPAIR_SHOP:'维修网点',SHOP_MANUAL:'网点填写',MANUAL:'人工录入',FIXED_AMOUNT:'固定金额',PERCENTAGE:'比例',CORRECTION:'纠正说明'}
export function label(value:unknown):string {if(value==null)return '未填写';if(typeof value==='boolean')return value?'是':'否';return states[String(value)]??String(value)}
const fields:Record<string,string>={id:'记录编号',caseId:'案件编号',workOrderId:'案件编号',rowNumber:'文件行号',sequence:'序号',description:'项目/说明',quantity:'数量',unitPrice:'原始单价（元）',amount:'金额（元）',total:'合计（元）',originalTotal:'原始合计（元）',originalUnitPrice:'原始单价（元）',originalAmount:'原始行金额（元）',allocatedMarkup:'分摊加价（元）',externalUnitPrice:'对外展示单价（元）',externalAmount:'对外行金额（元）',markupAmount:'加价金额（元）',markupValue:'加价值',markupMode:'加价方式',mode:'加价方式',version:'版本',basisVersion:'依据版本',createdAt:'记录时间',occurredAt:'业务时间',deadline:'截止时间',reason:'原因',publicNote:'公开说明',internalNote:'内部说明',note:'备注',kind:'记录类型',status:'状态',source:'来源',text:'评价内容',score:'评分',transactionNo:'流水号',direction:'资金方向',claimNo:'报案号',businessNo:'工单号',lines:'明细',photos:'照片快照',fileId:'照片编号',fileVersion:'文件版本',name:'文件名',currency:'币种',actorRole:'操作身份',confirmedBy:'确认身份',assignmentVersion:'派单版本',shopId:'网点编号',priceSnapshot:'原价快照',case_id:'匹配案件',error_code:'错误类型',errorCode:'错误类型',confirmed:'人工已确认'}
export function fieldLabel(key:string){return fields[key]??key}
export function records(value:unknown):Record<string,unknown>[] {if(typeof value==='string'){if(!value)return [];try{value=JSON.parse(value)}catch{return [{description:value}]}} if(Array.isArray(value))return value.map(v=>v!==null&&typeof v==='object'?v as Record<string,unknown>:{description:v});if(value&&typeof value==='object')return [value as Record<string,unknown>];return []}
export function displayValue(key:string,value:unknown){return /(?:At|deadline)$/.test(key)&&typeof value==='string'?localTime(value):label(value)}
export function localTime(value:string){const normalized=/^\d{4}-\d{2}-\d{2} \d{2}:/.test(value)?value.replace(' ','T')+'+08:00':value;const d=new Date(normalized);return Number.isNaN(d.getTime())?value:d.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}
export function chinaInput(value:string|null){if(!value)return '';const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const get=(type:string)=>parts.find(p=>p.type===type)?.value;return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`}
export function deadlinePayload(value:string){if(!value)return null;if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))throw Error('请选择有效的中国时间');return value+':00+08:00'}
export interface QuoteDraft {description:string;quantity:string;unitPrice:string}
export function quotePayload(lines:QuoteDraft[]){if(!lines.length)throw Error('请至少填写一项报价');return lines.map((line,index)=>{if(!line.description.trim())throw Error(`第${index+1}项请填写项目名称`);if(!/^\d+$/.test(line.quantity)||Number(line.quantity)<1||Number(line.quantity)>2147483647)throw Error(`第${index+1}项数量须为正整数`);if(!/^\d+(?:\.\d{1,2})?$/.test(line.unitPrice))throw Error(`第${index+1}项单价须为非负金额，最多2位小数`);return {description:line.description.trim(),quantity:Number(line.quantity),unitPrice:line.unitPrice}})}
