package com.evinsurance.platform.workorder.domain;

public enum WorkOrderStatus {
    DRAFT,
    PENDING_DISPATCH,
    PENDING_ACCEPTANCE,
    PENDING_ARRIVAL,
    ARRIVAL_EXCEPTION,
    ARRIVED,
    WAITING_QUOTE,
    QUOTE_REVIEWING,
    WAITING_INSURER_ASSESSMENT,
    WAITING_REPAIR_AUTHORIZATION,
    REPAIRING,
    WAITING_OWNER_CONFIRMATION,
    WAITING_INSURER_PAYMENT,
    WAITING_SHOP_SETTLEMENT,
    COMPLETED,
    CANCELLED,
    CLOSED
}
