<script setup lang="ts">
import {ref} from 'vue'
import {httpClient} from '@/shared/http/client'
const props=defineProps<{caseId:string}>()
const address=ref('合成测试地址'),latitude=ref(22.5),longitude=ref(114),otherLat=ref(22.6),otherLon=ref(114.1),result=ref(''),error=ref(''),page=ref(1)
async function query(path:string){try{result.value=JSON.stringify((await httpClient.get(`/maps/${path}`)).data.data,null,2);error.value=''}catch(e){error.value=e instanceof Error?e.message:'查询失败'}}
function select(event:MouseEvent){const box=(event.currentTarget as SVGElement).getBoundingClientRect();longitude.value=113.9+(event.clientX-box.left)/box.width*.2;latitude.value=22.6-(event.clientY-box.top)/box.height*.2;query(`reverse?latitude=${latitude.value}&longitude=${longitude.value}`)}
</script>
<template><section class="map"><h2>Mock 地图验证</h2><p>下图为合成坐标网格；距离为直线距离，不代表真实地址、道路或导航路线。</p><input v-model="address" aria-label="模拟地址"><button @click="query(`search?query=${encodeURIComponent(address)}`)">地址搜索</button><button @click="query(`geocode?address=${encodeURIComponent(address)}`)">正向编码</button><svg viewBox="0 0 400 160" role="img" aria-label="点击模拟网格选点" @click="select"><rect width="400" height="160" fill="#edf4fa"/><path d="M0 80H400M100 0V160M200 0V160M300 0V160" stroke="#bccbda"/><text x="20" y="30">点击网格选点并执行逆向编码</text></svg><label>纬度<input v-model.number="latitude" type="number" step="any"></label><label>经度<input v-model.number="longitude" type="number" step="any"></label><button @click="query(`reverse?latitude=${latitude}&longitude=${longitude}`)">逆向编码</button><label>目标纬度<input v-model.number="otherLat" type="number" step="any"></label><label>目标经度<input v-model.number="otherLon" type="number" step="any"></label><button @click="query(`distance?fromLat=${latitude}&fromLon=${longitude}&toLat=${otherLat}&toLon=${otherLon}`)">直线距离</button><button @click="query(`cases/${props.caseId}/shops?page=${page}&size=20`)">当前区域网点（模拟坐标）</button><input v-model.number="page" type="number" min="1" aria-label="网点页码"><p role="alert">{{ error }}</p><pre>{{ result }}</pre></section></template>
<style scoped>.map{padding:20px;border:1px solid #ddd;margin:20px 0}svg{display:block;width:100%;max-width:500px;cursor:crosshair}input,button{margin:6px}pre{white-space:pre-wrap}</style>
