<script setup lang="ts">
import PhotoPicker from '@/shared/ui/PhotoPicker.vue'
import RecordList from '@/shared/ui/RecordList.vue'
import {label,localTime} from '@/shared/ui/presentation'
import {computed,onMounted,ref,watch} from 'vue'
import {currentUser,httpClient} from '@/shared/http/client'
interface Complaint {id:string;caseId:string;status:string;version:number;description:string;createdAt:string;photos:unknown[]}
const props=defineProps<{caseId:string;status:string;refreshToken?:number}>()
const owner=computed(()=>currentUser.value?.roles.includes('OWNER')),admin=computed(()=>currentUser.value?.roles.includes('ADMIN')),cs=computed(()=>currentUser.value?.roles.includes('CUSTOMER_SERVICE'))
const records=ref<Complaint[]>([]),total=ref(0),page=ref(1),selected=ref<Complaint>(),history=ref(''),historyPage=ref(1),historyTotal=ref(0),busy=ref(false),message=ref(''),description=ref(''),photos=ref<string[]>([]),publicNote=ref(''),internalNote=ref(''),pending=ref<{body:string;key:string}>()
const canCreate=computed(()=>owner.value&&['REPAIRING','WAITING_OWNER_CONFIRMATION','COMPLETED','WAITING_INSURER_PAYMENT','WAITING_SHOP_SETTLEMENT'].includes(props.status))
const next=computed(()=>selected.value&&({SUBMITTED:'PROCESSING',PROCESSING:'RESOLVED',RESOLVED:'CLOSED'} as Record<string,string>)[selected.value.status])
async function load(){const result=(await httpClient.get<{data:{records:Complaint[];total:number}}>(`/complaints/cases/${props.caseId}`,{params:{page:page.value,size:20}})).data.data;records.value=result.records;total.value=result.total}
async function run(action:()=>Promise<void>){busy.value=true;message.value='';try{await action()}catch(e){message.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
async function post(path:string,body:unknown){const serialized=JSON.stringify({path,body});if(pending.value?.body!==serialized)pending.value={body:serialized,key:crypto.randomUUID()};const result=(await httpClient.post<{data:Complaint}>(path,body,{headers:{'Idempotency-Key':pending.value.key}})).data.data;pending.value=undefined;return result}
async function create(){if(!description.value.trim())throw Error('请填写投诉正文');selected.value=await post(`/complaints/cases/${props.caseId}`,{description:description.value,photoIds:photos.value});description.value='';photos.value=[];message.value='投诉已提交，原文不可修改';await load();await select(selected.value)}
async function select(row:Complaint){selected.value=(await httpClient.get<{data:Complaint}>(`/complaints/${row.id}`)).data.data;const result=(await httpClient.get<{data:{records:unknown[];total:number}}>(`/complaints/${row.id}/history`,{params:{page:historyPage.value,size:20}})).data.data;history.value=JSON.stringify(result.records,null,2);historyTotal.value=result.total}
async function handle(correction:boolean){if(!selected.value)return;const row=await post(`/complaints/${selected.value.id}/${correction?'corrections':'handle'}`,{expectedVersion:selected.value.version,publicNote:publicNote.value,...(correction?{}:{status:next.value,internalNote:internalNote.value})});publicNote.value='';internalNote.value='';message.value='处理记录已追加';await load();await select(row)}
onMounted(()=>run(load));watch(()=>props.refreshToken,()=>run(load))
</script>
<template><section class="complaint"><h2>独立投诉</h2><p>投诉不改变维修状态，不自动影响评分；原文及处理历史保留。</p><p role="status">{{ message }}</p><button :disabled="busy" @click="run(load)">刷新</button><div v-if="canCreate"><label>投诉正文<textarea v-model="description" maxlength="2000"/></label><PhotoPicker v-model="photos" :case-id="caseId" :refresh-token="refreshToken"/><button :disabled="busy" @click="run(create)">提交投诉</button></div><p>共 {{ total }} 条</p><article v-for="row in records" :key="row.id"><p>{{ label(row.status) }} · {{ localTime(row.createdAt) }} · {{ row.description }}</p><button :disabled="busy" @click="historyPage=1;run(()=>select(row))">查看处理历史</button></article><button :disabled="busy||page<=1" @click="page--;run(load)">上一页</button><button :disabled="busy||page*20>=total" @click="page++;run(load)">下一页</button><div v-if="selected"><h3>{{ label(selected.status) }} 处理历史</h3><RecordList :value="history"/><button :disabled="busy||historyPage<=1" @click="historyPage--;run(()=>select(selected!))">上一页</button><button :disabled="busy||historyPage*20>=historyTotal" @click="historyPage++;run(()=>select(selected!))">下一页</button><div v-if="admin||cs"><label>公开处理/纠正说明<textarea v-model="publicNote" maxlength="2000"/></label><label v-if="admin">管理员内部说明<textarea v-model="internalNote" maxlength="2000"/></label><button v-if="admin&&next" :disabled="busy" @click="run(()=>handle(false))">转为 {{ label(next) }}</button><button v-if="cs" :disabled="busy" @click="run(()=>handle(true))">客服追加纠正说明</button></div></div></section></template>
<style scoped>.complaint{padding:20px;margin:20px 0;border:1px solid #ddd}label{display:block;margin:10px 0}input,textarea{width:100%;box-sizing:border-box}button{margin:6px}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style>
