<script setup lang="ts">
import {label,localTime} from '@/shared/ui/presentation'
import {computed,onMounted,ref,watch} from 'vue'
import {currentUser,httpClient} from '@/shared/http/client'
import FundsImportPanel from './FundsImportPanel.vue'
interface Direction {target:string|null;net:string;status:string}
interface Funds {caseId:string;version:number;currency:string;receivable?:Direction;payable:Direction}
interface Entry {id:string;direction:string;amount:string;occurredAt:string;reversed:boolean;note?:string}
const props=defineProps<{caseId:string;refreshToken?:number}>(),base=`/funds/cases/${props.caseId}`
const data=ref<Funds>(),entries=ref<Entry[]>([]),total=ref(0),page=ref(1),busy=ref(false),message=ref(''),direction=ref('RECEIVE'),amount=ref(''),reason=ref(''),number=ref(''),time=ref(''),note=ref(''),pending=ref<{body:string;key:string}>()
const cs=computed(()=>currentUser.value?.roles.includes('CUSTOMER_SERVICE'))
async function load(){data.value=(await httpClient.get<{data:Funds}>(base)).data.data;const result=(await httpClient.get<{data:{records:Entry[];total:number}}>(`${base}/entries`,{params:{page:page.value,size:20}})).data.data;entries.value=result.records;total.value=result.total}
async function run(action:()=>Promise<void>){busy.value=true;message.value='';try{await action()}catch(error){message.value=error instanceof Error?error.message:'操作失败'}finally{busy.value=false}}
async function post(path:string,body:unknown){const serialized=JSON.stringify({path,body});if(pending.value?.body!==serialized)pending.value={body:serialized,key:crypto.randomUUID()};await httpClient.post(path,body,{headers:{'Idempotency-Key':pending.value.key}});pending.value=undefined;message.value='记录已保存，历史保留';await load()}
async function target(){if(data.value)await post(`${base}/targets`,{expectedVersion:data.value.version,direction:direction.value,amount:amount.value===''?null:amount.value,reason:reason.value})}
async function entry(){if(data.value)await post(`${base}/entries`,{expectedVersion:data.value.version,direction:direction.value,transactionNo:number.value,amount:amount.value,occurredAt:time.value,note:note.value})}
async function reverse(id:string){if(data.value)await post(`${base}/entries/${id}/reverse`,{expectedVersion:data.value.version,reason:reason.value})}
async function download(){const response=await httpClient.get(`${base}/export`,{params:{page:page.value,size:20},responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=`ledger-${props.caseId}-${page.value}.csv`;a.click();URL.revokeObjectURL(url)}
onMounted(()=>run(load));watch(()=>props.refreshToken,()=>run(load))
</script>
<template><section class="funds"><h2>资金记录（仅记账）</h2><p role="status">{{ message }}</p><button :disabled="busy" @click="run(load)">刷新</button><template v-if="data"><p>币种 CNY，单位元；资金版本 {{ data.version }}</p><p v-if="data.receivable">应收 {{ data.receivable.target??'未定' }}；净实收 {{ data.receivable.net }}；{{ label(data.receivable.status) }}</p><p>应付 {{ data.payable.target??'未定' }}；净实付 {{ data.payable.net }}；{{ label(data.payable.status) }}</p><div v-if="cs"><label>方向<select v-model="direction"><option value="RECEIVE">保司→平台</option><option value="PAY">平台→网点</option></select></label><label>金额（最多2位小数，应付未定可留空）<input v-model="amount" inputmode="decimal"/></label><label>目标修订/冲销原因<textarea v-model="reason" maxlength="2000"/></label><button :disabled="busy" @click="run(target)">追加目标版本</button><label>唯一流水号<input v-model="number" maxlength="128"/></label><label>业务时间（ISO-8601含时区，例如2026-10-10T12:00:00+08:00）<input v-model="time"/></label><label>内部备注<textarea v-model="note" maxlength="2000"/></label><p>实付须收车完成、应付明确且保险回款结清；撤回收车后历史资金保留。实际流水大于0，超额拒绝；冲销后重录使用新流水号。</p><button :disabled="busy" @click="run(entry)">追加实际流水</button></div></template><h3>分笔历史（共 {{ total }} 条）</h3><article v-for="row in entries" :key="row.id"><p>{{ label(row.direction) }} {{ row.amount }}元 · {{ localTime(row.occurredAt) }} · {{ row.reversed?'已冲销':'有效' }}</p><p v-if="row.note">{{ row.note }}</p><button v-if="cs&&!row.reversed" :disabled="busy" @click="run(()=>reverse(row.id))">填写原因后整笔冲销</button></article><button :disabled="busy||page<=1" @click="page--;run(load)">上一页</button><button :disabled="busy||page*20>=total" @click="page++;run(load)">下一页</button><button :disabled="busy" @click="run(download)">导出当前页（权限过滤）</button><FundsImportPanel v-if="cs" @changed="run(load)"/></section></template>
<style scoped>.funds{margin:20px 0;padding:20px;border:1px solid #ddd}label{display:block;margin:10px 0}input,textarea,select{width:100%;box-sizing:border-box}button{margin:6px}</style>
