<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElButton, ElCard, ElDatePicker, ElDialog, ElForm, ElFormItem, ElInput, ElMessage, ElMessageBox, ElOption, ElSelect, ElTable, ElTableColumn, ElTag } from 'element-plus'
import { currentUser, httpClient } from '@/shared/http/client'
import { statusLabels, workOrderApi, type DraftForm, type RegionOption, type WorkOrder, type WorkOrderStatus } from './work-orders'

const api=workOrderApi(httpClient),router=useRouter(),loading=ref(false),rows=ref<WorkOrder[]>([]),total=ref(0),page=ref(1)
const status=ref(''),query=ref(''),dialog=ref(false),saving=ref(false),regions=ref<RegionOption[]>([])
const isAdmin=computed(()=>currentUser.value?.roles.includes('ADMIN')===true)
const blank=():DraftForm=>({insuranceCompany:'',claimNo:'',claimReportedAt:'',ownerName:'',ownerPhone:'',policyNo:'',vehicleBrand:'',vehicleModel:'',vehicleVin:'',vehiclePlate:'',vehicleOtherIdentifier:'',accidentAt:'',accidentRegionId:'',accidentAddress:'',accidentDescription:''})
const form=reactive<DraftForm>(blank())
async function load(){loading.value=true;try{const result=await api.list(page.value,status.value,query.value.trim());rows.value=result.records;total.value=result.total}catch(error){ElMessage.error(error instanceof Error?error.message:'加载失败')}finally{loading.value=false}}
async function create(){saving.value=true;try{const created=await api.create(form);dialog.value=false;Object.assign(form,blank());ElMessage.success('草稿已创建');await router.push(`/work-orders/${created.id}`)}catch(error){ElMessage.error(error instanceof Error?error.message:'创建失败')}finally{saving.value=false}}
async function configureDuplicates(){try{const current=await api.configuration();const days=await ElMessageBox.prompt('疑似重复的相近/短期天数（1—365）','重复判断配置',{inputValue:String(current.possibleDuplicateDays),inputPattern:/^(?:[1-9]|[1-9]\d|[12]\d\d|3[0-5]\d|36[0-5])$/,inputErrorMessage:'请输入 1—365 的整数'});const reason=await ElMessageBox.prompt('请输入本次修改原因','重复判断配置',{inputValidator:value=>Boolean(value.trim())||'原因必填'});await api.updateConfiguration(Number(days.value),reason.value.trim());ElMessage.success('重复判断时间窗口已更新')}catch(error){if(error instanceof Error&&error.message)ElMessage.error(error.message)}}
onMounted(async()=>{await load();try{regions.value=(await api.regions()).records}catch(error){ElMessage.error(error instanceof Error?error.message:'区域加载失败')}})
</script>

<template>
  <main class="work-page"><ElCard shadow="never"><template #header><div class="card-header"><div><h1>保险案件</h1><p>草稿、重复判断、派单与到店前异常流程</p></div><div class="actions"><ElButton @click="router.push('/')">返回首页</ElButton><ElButton v-if="isAdmin" @click="configureDuplicates">重复判断配置</ElButton><ElButton type="primary" @click="dialog=true">新建草稿</ElButton></div></div></template>
    <div class="filters"><ElInput v-model="query" clearable placeholder="案件号 / 报案号 / 手机号" @keyup.enter="page=1;load()"/><ElSelect v-model="status" clearable placeholder="全部状态"><ElOption v-for="(label,key) in statusLabels" :key="key" :label="label" :value="key"/></ElSelect><ElButton @click="page=1;load()">查询</ElButton></div>
    <ElTable v-loading="loading" :data="rows" @row-click="row=>router.push(`/work-orders/${row.id}`)"><ElTableColumn prop="businessNo" label="案件号" min-width="190"><template #default="{row}">{{ row.businessNo || '草稿未编号' }}</template></ElTableColumn><ElTableColumn prop="claimNo" label="报案号" min-width="150"/><ElTableColumn prop="ownerName" label="车主"/><ElTableColumn prop="ownerPhone" label="手机号" min-width="130"/><ElTableColumn label="车辆" min-width="160"><template #default="{row}">{{ row.vehicleBrand }} {{ row.vehicleModel }}</template></ElTableColumn><ElTableColumn label="状态"><template #default="{row}"><ElTag>{{ statusLabels[row.status as WorkOrderStatus] }}</ElTag></template></ElTableColumn></ElTable>
    <div class="pager"><ElButton :disabled="page<=1" @click="page--;load()">上一页</ElButton><span>第 {{ page }} 页，共 {{ total }} 条</span><ElButton :disabled="page*20>=total" @click="page++;load()">下一页</ElButton></div>
  </ElCard>
  <ElDialog v-model="dialog" title="新建案件草稿" width="820px"><ElForm label-position="top"><div class="form-grid"><ElFormItem label="保险公司"><ElInput v-model="form.insuranceCompany"/></ElFormItem><ElFormItem label="报案号"><ElInput v-model="form.claimNo"/></ElFormItem><ElFormItem label="报案时间（选填）"><ElDatePicker v-model="form.claimReportedAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></ElFormItem><ElFormItem label="车主姓名"><ElInput v-model="form.ownerName"/></ElFormItem><ElFormItem label="车主手机"><ElInput v-model="form.ownerPhone"/></ElFormItem><ElFormItem label="保单号（选填）"><ElInput v-model="form.policyNo"/></ElFormItem><ElFormItem label="车辆品牌"><ElInput v-model="form.vehicleBrand"/></ElFormItem><ElFormItem label="车辆型号"><ElInput v-model="form.vehicleModel"/></ElFormItem><ElFormItem label="车架号 / VIN"><ElInput v-model="form.vehicleVin"/></ElFormItem><ElFormItem label="车辆牌照"><ElInput v-model="form.vehiclePlate"/></ElFormItem><ElFormItem label="保险认可的其他车辆编号"><ElInput v-model="form.vehicleOtherIdentifier"/></ElFormItem><ElFormItem label="事故时间"><ElDatePicker v-model="form.accidentAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></ElFormItem><ElFormItem label="事故区域"><ElSelect v-model="form.accidentRegionId" filterable placeholder="选择区域"><ElOption v-for="item in regions" :key="item.id" :label="`${item.name}（${item.code}）`" :value="String(item.id)"/></ElSelect></ElFormItem><ElFormItem label="详细地址（选填）"><ElInput v-model="form.accidentAddress"/></ElFormItem><ElFormItem class="wide" label="事故说明"><ElInput v-model="form.accidentDescription" type="textarea"/></ElFormItem></div></ElForm><p class="hint">正式提交时，车架号、车辆牌照、其他车辆编号至少填写一项；案件数据来源和当前负责人由系统填写。</p><template #footer><ElButton @click="dialog=false">取消</ElButton><ElButton type="primary" :loading="saving" @click="create">保存草稿</ElButton></template></ElDialog>
  </main>
</template>

<style scoped>.work-page{padding:32px;min-height:100vh}.filters{display:grid;grid-template-columns:minmax(260px,1fr) 180px auto;gap:12px;margin-bottom:20px}.pager{display:flex;justify-content:flex-end;align-items:center;gap:16px;margin-top:20px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 20px}.wide{grid-column:1/-1}.hint{color:#667085}.el-table{cursor:pointer}</style>
