<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElButton, ElCard, ElDatePicker, ElDescriptions, ElDescriptionsItem, ElDialog, ElForm, ElFormItem, ElInput, ElMessage, ElMessageBox, ElOption, ElSelect, ElTable, ElTableColumn, ElTag } from 'element-plus'
import { ApiError } from '@/shared/http/create-client'
import { currentUser, httpClient } from '@/shared/http/client'
import { statusLabels, workOrderApi, type CriticalForm, type DraftForm, type History, type RegionOption, type ShopOption, type WorkOrder } from './work-orders'

const route=useRoute(),router=useRouter(),id=String(route.params.id),api=workOrderApi(httpClient)
const order=ref<WorkOrder>(),history=ref<History[]>([]),shops=ref<ShopOption[]>([]),regions=ref<RegionOption[]>([]),shopId=ref<number>()
const busy=ref(false),editDialog=ref(false),criticalDialog=ref(false)
const isAdmin=computed(()=>currentUser.value?.roles.includes('ADMIN')===true)
const adminOnlyCancellation=computed(()=>order.value!==undefined&&['ARRIVED','WAITING_QUOTE','QUOTE_REVIEWING','WAITING_INSURER_ASSESSMENT','WAITING_REPAIR_AUTHORIZATION','REPAIRING','WAITING_OWNER_CONFIRMATION','WAITING_INSURER_PAYMENT','WAITING_SHOP_SETTLEMENT','COMPLETED'].includes(order.value.status))
const blankDraft=():DraftForm=>({insuranceCompany:'',claimNo:'',claimReportedAt:'',ownerName:'',ownerPhone:'',policyNo:'',vehicleBrand:'',vehicleModel:'',vehicleVin:'',vehiclePlate:'',vehicleOtherIdentifier:'',accidentAt:'',accidentRegionId:'',accidentAddress:'',accidentDescription:''})
const edit=reactive<DraftForm>(blankDraft())
const critical=reactive<CriticalForm>({insuranceCompany:'',claimNo:'',vehicleVin:'',vehiclePlate:'',vehicleOtherIdentifier:'',reason:''})
const local=(value?:string)=>value?.slice(0,19)??''
const assignmentVersion=()=>{const version=order.value?.currentAssignment?.assignmentVersion;if(!version)throw new Error('当前派单版本不存在，请刷新后重试');return version}
async function load(){order.value=await api.detail(id);history.value=(await api.history(id)).records;if(order.value.status!=='DRAFT'&&order.value.status!=='CANCELLED'){shops.value=(await api.shops(id)).records}}
function openEdit(){if(!order.value)return;Object.assign(edit,{insuranceCompany:order.value.insuranceCompany??'',claimNo:order.value.claimNo??'',claimReportedAt:local(order.value.claimReportedAt),ownerName:order.value.ownerName??'',ownerPhone:order.value.ownerPhone??'',policyNo:order.value.policyNo??'',vehicleBrand:order.value.vehicleBrand??'',vehicleModel:order.value.vehicleModel??'',vehicleVin:order.value.vehicleVin??'',vehiclePlate:order.value.vehiclePlate??'',vehicleOtherIdentifier:order.value.vehicleOtherIdentifier??'',accidentAt:local(order.value.accidentAt),accidentRegionId:String(order.value.accidentRegionId??''),accidentAddress:order.value.accidentAddress??'',accidentDescription:order.value.accidentDescription??''});editDialog.value=true}
function openCritical(){if(!order.value)return;Object.assign(critical,{insuranceCompany:order.value.insuranceCompany??'',claimNo:order.value.claimNo??'',vehicleVin:order.value.vehicleVin??'',vehiclePlate:order.value.vehiclePlate??'',vehicleOtherIdentifier:order.value.vehicleOtherIdentifier??'',reason:''});criticalDialog.value=true}
async function saveDraft(){busy.value=true;try{order.value=await api.update(id,edit);editDialog.value=false;ElMessage.success('草稿已保存')}catch(error){ElMessage.error(error instanceof Error?error.message:'保存失败')}finally{busy.value=false;await load()}}
async function deleteDraft(){try{await ElMessageBox.confirm('删除后不可恢复，确定删除此草稿吗？','删除草稿',{type:'warning'});await api.deleteDraft(id);ElMessage.success('草稿已删除');await router.push('/work-orders')}catch(error){if(error instanceof Error&&error.message)ElMessage.error(error.message)}}
async function submit(){busy.value=true;try{order.value=await api.submit(id);ElMessage.success('已生成正式案件')}catch(error){if(error instanceof ApiError&&error.code==='POSSIBLE_DUPLICATE'){try{const result=await ElMessageBox.prompt('发现疑似重复案件。请输入继续创建原因：','疑似重复案件',{inputValidator:value=>Boolean(value.trim())||'原因必填'});order.value=await api.submit(id,true,result.value.trim());ElMessage.success('已记录原因并生成正式案件')}catch{ElMessage.info('已取消提交')}}else ElMessage.error(error instanceof Error?error.message:'提交失败')}finally{busy.value=false;await load()}}
async function saveCritical(){busy.value=true;try{order.value=await api.critical(id,{...critical,reason:critical.reason.trim()});criticalDialog.value=false;ElMessage.success('关键字段已更新并审计')}catch(error){ElMessage.error(error instanceof Error?error.message:'更新失败')}finally{busy.value=false;await load()}}
async function dispatchNew(confirmPossibleDuplicate=false,duplicateReason:string|null=null){if(!shopId.value){ElMessage.warning('请选择维修网点');return}try{order.value=await api.dispatch(id,shopId.value,confirmPossibleDuplicate,duplicateReason);ElMessage.success('已派单')}catch(error){if(error instanceof ApiError&&error.code==='POSSIBLE_DUPLICATE'&&!confirmPossibleDuplicate){const result=await ElMessageBox.prompt('该车主在此网点存在短期案件。请输入继续派单原因：','疑似重复案件',{inputValidator:value=>Boolean(value.trim())||'原因必填'});await dispatchNew(true,result.value.trim())}else throw error}}
async function reassign(){if(!shopId.value||!order.value){ElMessage.warning('请选择维修网点');return}const result=await ElMessageBox.prompt('请输入改派原因','改派',{inputValidator:value=>Boolean(value.trim())||'原因必填'});let transferDescription:string|null=null;let vehicleNotArrivedConfirmed=false;if(order.value.status==='PENDING_ARRIVAL'||order.value.status==='ARRIVAL_EXCEPTION'){await ElMessageBox.confirm('请确认车辆尚未到店。','改派确认',{type:'warning'});vehicleNotArrivedConfirmed=true}if(order.value.status==='ARRIVED'){const transfer=await ElMessageBox.prompt('车辆已到店，仅管理员可异常改派。请输入车辆转运说明：','异常改派',{inputValidator:value=>Boolean(value.trim())||'转运说明必填'});transferDescription=transfer.value.trim()}const value={shopId:shopId.value,assignmentVersion:assignmentVersion(),reason:result.value.trim(),vehicleNotArrivedConfirmed,transferDescription,confirmPossibleDuplicate:false};try{order.value=await api.reassign(id,value);ElMessage.success('已改派')}catch(error){if(error instanceof ApiError&&error.code==='POSSIBLE_DUPLICATE'){await ElMessageBox.confirm('目标网点存在短期重复案件，是否仍按刚才原因继续改派？','疑似重复案件',{type:'warning'});order.value=await api.reassign(id,{...value,confirmPossibleDuplicate:true});ElMessage.success('已记录原因并改派')}else throw error}}
async function cancelAssignment(){const result=await ElMessageBox.prompt('请输入取消派单原因','取消派单',{inputValidator:value=>Boolean(value.trim())||'原因必填'});order.value=await api.cancelAssignment(id,assignmentVersion(),result.value.trim());ElMessage.success('已取消派单')}
async function markArrivalException(){const result=await ElMessageBox.prompt('请输入到店异常原因','标记到店异常',{inputValidator:value=>Boolean(value.trim())||'原因必填'});order.value=await api.arrivalException(id,assignmentVersion(),result.value.trim());ElMessage.success('已进入到店异常')}
async function continueWaiting(){const result=await ElMessageBox.prompt('可填写继续等待说明','继续等待');order.value=await api.continueWaiting(id,assignmentVersion(),result.value.trim()||null);ElMessage.success('已恢复待到店')}
async function cancelWorkOrder(){const reason=await ElMessageBox.prompt('请输入取消原因','取消整个工单',{inputValidator:value=>Boolean(value.trim())||'取消原因必填'});const description=await ElMessageBox.prompt('请输入取消说明','取消整个工单',{inputValidator:value=>Boolean(value.trim())||'取消说明必填'});order.value=await api.cancelWorkOrder(id,{reason:reason.value.trim(),description:description.value.trim(),notifyOwner:window.confirm('是否记录为需要通知车主？'),notifyShop:window.confirm('是否记录为需要通知维修网点？')});ElMessage.success('工单已取消')}
async function run(action:()=>Promise<void>){busy.value=true;try{await action()}catch(error){if(error instanceof Error&&error.message)ElMessage.error(error.message)}finally{busy.value=false;await load()}}
onMounted(async()=>{try{regions.value=(await api.regions()).records;await load()}catch(error){ElMessage.error(error instanceof Error?error.message:'加载失败')}})
</script>

<template><main class="work-page"><ElCard v-if="order" shadow="never"><template #header><div class="card-header"><div><ElButton text @click="router.push('/work-orders')">← 返回案件</ElButton><h1>{{ order.businessNo || '案件草稿' }}</h1><ElTag>{{ statusLabels[order.status] }}</ElTag></div><div class="actions"><ElButton v-if="order.status==='DRAFT'" @click="openEdit">编辑草稿</ElButton><ElButton v-if="order.status==='DRAFT'" type="danger" plain @click="deleteDraft">删除草稿</ElButton><ElButton v-if="order.status==='DRAFT'" type="primary" :loading="busy" @click="submit">提交正式案件</ElButton><ElButton v-if="order.status!=='DRAFT'&&order.status!=='CANCELLED'&&order.status!=='CLOSED'" @click="openCritical">修改关键字段</ElButton><ElButton v-if="order.status!=='DRAFT'&&order.status!=='CANCELLED'&&order.status!=='CLOSED'&&order.status!=='COMPLETED'&&(!adminOnlyCancellation||isAdmin)" type="danger" plain :loading="busy" @click="run(cancelWorkOrder)">取消整个工单</ElButton></div></div></template>
  <ElDescriptions :column="3" border><ElDescriptionsItem label="报案号">{{ order.claimNo }}</ElDescriptionsItem><ElDescriptionsItem label="保险公司">{{ order.insuranceCompany }}</ElDescriptionsItem><ElDescriptionsItem label="数据来源">{{ order.dataSource }}</ElDescriptionsItem><ElDescriptionsItem label="当前负责人">{{ order.currentResponsibleId }}</ElDescriptionsItem><ElDescriptionsItem label="车主">{{ order.ownerName }}</ElDescriptionsItem><ElDescriptionsItem label="手机">{{ order.ownerPhone }}</ElDescriptionsItem><ElDescriptionsItem label="车辆">{{ order.vehicleBrand }} {{ order.vehicleModel }}</ElDescriptionsItem><ElDescriptionsItem label="VIN">{{ order.vehicleVin || '-' }}</ElDescriptionsItem><ElDescriptionsItem label="牌照/其他">{{ order.vehiclePlate || order.vehicleOtherIdentifier || '-' }}</ElDescriptionsItem><ElDescriptionsItem label="事故地址" :span="2">{{ order.accidentAddress || '未填写详细地址' }}</ElDescriptionsItem><ElDescriptionsItem label="事故时间">{{ order.accidentAt }}</ElDescriptionsItem><ElDescriptionsItem label="事故说明" :span="3">{{ order.accidentDescription }}</ElDescriptionsItem></ElDescriptions>
  <section v-if="['PENDING_DISPATCH','PENDING_ACCEPTANCE','PENDING_ARRIVAL','ARRIVAL_EXCEPTION','ARRIVED'].includes(order.status)" class="panel"><h2>派单与异常处理</h2><div class="inline"><ElSelect v-model="shopId" placeholder="选择服务区域内网点"><ElOption v-for="item in shops" :key="item.id" :label="item.name" :value="item.id"/></ElSelect><ElButton v-if="order.status==='PENDING_DISPATCH'" type="primary" :loading="busy" @click="run(()=>dispatchNew())">派单</ElButton><ElButton v-if="['PENDING_ACCEPTANCE','PENDING_ARRIVAL','ARRIVAL_EXCEPTION'].includes(order.status)||(order.status==='ARRIVED'&&isAdmin)" :loading="busy" @click="run(()=>reassign())">改派</ElButton><ElButton v-if="['PENDING_ACCEPTANCE','PENDING_ARRIVAL','ARRIVAL_EXCEPTION'].includes(order.status)" type="danger" plain :loading="busy" @click="run(cancelAssignment)">取消派单</ElButton><ElButton v-if="order.status==='PENDING_ARRIVAL'" :loading="busy" @click="run(markArrivalException)">标记到店异常</ElButton><ElButton v-if="order.status==='ARRIVAL_EXCEPTION'" :loading="busy" @click="run(continueWaiting)">继续等待</ElButton></div></section>
  <section class="panel"><h2>状态记录</h2><ElTable :data="history"><ElTableColumn prop="occurredAt" label="时间" min-width="180"/><ElTableColumn prop="action" label="动作"/><ElTableColumn prop="fromStatus" label="原状态"/><ElTableColumn prop="toStatus" label="新状态"/><ElTableColumn prop="reason" label="原因" min-width="260"/></ElTable></section>
 </ElCard>
 <ElDialog v-model="editDialog" title="编辑案件草稿" width="820px"><ElForm label-position="top"><div class="form-grid"><ElFormItem label="保险公司"><ElInput v-model="edit.insuranceCompany"/></ElFormItem><ElFormItem label="报案号"><ElInput v-model="edit.claimNo"/></ElFormItem><ElFormItem label="报案时间（选填）"><ElDatePicker v-model="edit.claimReportedAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></ElFormItem><ElFormItem label="车主姓名"><ElInput v-model="edit.ownerName"/></ElFormItem><ElFormItem label="车主手机"><ElInput v-model="edit.ownerPhone"/></ElFormItem><ElFormItem label="保单号（选填）"><ElInput v-model="edit.policyNo"/></ElFormItem><ElFormItem label="车辆品牌"><ElInput v-model="edit.vehicleBrand"/></ElFormItem><ElFormItem label="车辆型号"><ElInput v-model="edit.vehicleModel"/></ElFormItem><ElFormItem label="车架号 / VIN"><ElInput v-model="edit.vehicleVin"/></ElFormItem><ElFormItem label="车辆牌照"><ElInput v-model="edit.vehiclePlate"/></ElFormItem><ElFormItem label="其他车辆编号"><ElInput v-model="edit.vehicleOtherIdentifier"/></ElFormItem><ElFormItem label="事故时间"><ElDatePicker v-model="edit.accidentAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></ElFormItem><ElFormItem label="事故区域"><ElSelect v-model="edit.accidentRegionId" filterable><ElOption v-for="item in regions" :key="item.id" :label="`${item.name}（${item.code}）`" :value="String(item.id)"/></ElSelect></ElFormItem><ElFormItem label="详细地址（选填）"><ElInput v-model="edit.accidentAddress"/></ElFormItem><ElFormItem class="wide" label="事故说明"><ElInput v-model="edit.accidentDescription" type="textarea"/></ElFormItem></div></ElForm><template #footer><ElButton @click="editDialog=false">取消</ElButton><ElButton type="primary" :loading="busy" @click="saveDraft">保存</ElButton></template></ElDialog>
 <ElDialog v-model="criticalDialog" title="修改关键字段" width="680px"><ElForm label-position="top"><div class="form-grid"><ElFormItem label="保险公司"><ElInput v-model="critical.insuranceCompany"/></ElFormItem><ElFormItem label="报案号"><ElInput v-model="critical.claimNo"/></ElFormItem><ElFormItem label="车架号 / VIN"><ElInput v-model="critical.vehicleVin"/></ElFormItem><ElFormItem label="车辆牌照"><ElInput v-model="critical.vehiclePlate"/></ElFormItem><ElFormItem label="其他车辆编号"><ElInput v-model="critical.vehicleOtherIdentifier"/></ElFormItem><ElFormItem class="wide" label="修改原因"><ElInput v-model="critical.reason" type="textarea"/></ElFormItem></div></ElForm><template #footer><ElButton @click="criticalDialog=false">取消</ElButton><ElButton type="primary" :loading="busy" @click="saveCritical">保存并审计</ElButton></template></ElDialog>
</main></template>

<style scoped>.work-page{padding:32px;min-height:100vh}.panel{margin-top:28px}.panel h2{font-size:18px}.inline{display:flex;align-items:center;flex-wrap:wrap;gap:12px;margin:12px 0}.inline .el-select{width:260px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(180px,1fr));gap:0 20px}.wide{grid-column:1/-1}</style>
